quynh commit
khoa165/mentorship-website-data pull request #12
Opened 2024-03-24 03:19 UTC by quynhtran158

2024-03-24 06:29 UTC, khoa165 approved these changes

2024-03-24 06:31 UTC, khoa165 requested changes
Request change related to URL

2024-03-24 06:31 UTC, khoa165 commented on index.js
> +                avatar: '',
If you are not comfortable with displaying your pic on the website, use this one `https://res.cloudinary.com/khoa165/image/upload/v1711083640/viettech/placeholder.jpg`

2024-03-26 05:56 UTC, khoa165 requested changes
Ủa cái commit mới nhất của e đổi hết styling rồi huhu, với merge main đi để fix conflict lun

2024-03-26 16:38 UTC, closed without merging

2024-03-26 17:40 UTC, quynhtran158 commented
Dạ, VSC em cứ save là auto đổi format cả indentation với double quotation mark TvT Em thử sửa rồi mà không được nên em mới sync fork, làm lại commit mới trên terminal rồi á anh